### ISSUE TITLE
GitHub actions maintain workflow issue

### ISSUE THREAD

**Issue by iUnstable0** [hackclub/webring#104]
Currently, the "maintain" action is malfunctioning because the main branch is protected.

Would you prefer to unprotect the branch or modify the action to create a pull request and merge it?

There's also a potential issue with the current workflow.yml. Won't this configuration lead to an infinite loop, given that it's triggered on every push to the master branch

```yaml
on:
  push:
    branches: [ master ]
  schedule:
    - cron: 0/15 * * * *
```

and pushes the new changes back to the branch

```yaml
- name: Push changes
  uses: ad-m/github-push-action@master
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
    branch: ${{ github.ref }}
```

???

Also, I've noticed that it should reference "main" and not "master".

I suggest removing the push hook and keeping only cron.
